"""Generate CLI reference pages from the cyclopts app."""

from pathlib import Path

from cyclopts.docs.markdown import generate_markdown_docs

from pinch_backend.cli.app import app

OUT_DIR = Path(__file__).parent.parent / "docs" / "pages" / "reference" / "cli"
BANNER = "<!-- Generated by scripts/gen_cli_docs.py — do not edit. Regenerate: just docs-cli -->"


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    content = generate_markdown_docs(app, recursive=True).strip()
    (OUT_DIR / "index.md").write_text(f"{BANNER}\n\n# pinch-dev CLI\n\n{content}\n")


if __name__ == "__main__":
    main()
